export type ProductColor = {
  name: string;
  hex: string;
};

export type Product = {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  price: number;
  compareAtPrice?: number;
  category: string;
  collections: string[];
  audience: string[];
  description: string;
  details: string[];
  fit: string;
  fabric: string;
  image: string;
  imagePosition?: string;
  colors: ProductColor[];
  sizes: string[];
  badge?: string;
  rating: number;
  reviewCount: number;
};

const coreColors = {
  cream: { name: "Warm Cream", hex: "#e9e1d2" },
  oatmeal: { name: "Oatmeal", hex: "#cfc0a6" },
  gray: { name: "Heather Gray", hex: "#aaa9a5" },
  sage: { name: "Resting Sage", hex: "#8e9a83" },
  blue: { name: "Dusty Blue", hex: "#788d9d" },
  terra: { name: "Soft Terracotta", hex: "#b77f67" },
  rose: { name: "Soft Rose", hex: "#c89991" },
  ink: { name: "Washed Ink", hex: "#45484a" },
};

export const products: Product[] = [
  {
    id: "rst-tee-001",
    slug: "the-home-tee",
    name: "The Home Tee",
    shortName: "Home Tee",
    price: 32,
    category: "Tees",
    collections: ["best-sellers", "women", "men", "matching"],
    audience: ["Mom", "Dad"],
    description: "The tee you reach for the moment the day is done. Substantial, brushed-soft, and relaxed without losing its shape.",
    details: ["Pre-washed for a lived-in handfeel", "Reinforced neckline that stays flat", "Shrink-resistant wash treatment", "Designed and wear-tested for real family life"],
    fit: "Relaxed, slightly oversized. Size down for a closer fit.",
    fabric: "100% long-staple combed cotton, 6.5 oz.",
    image: "/images/tees-flatlay.png",
    colors: [coreColors.cream, coreColors.oatmeal, coreColors.sage, coreColors.blue, coreColors.ink],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    badge: "Best seller",
    rating: 4.9,
    reviewCount: 184,
  },
  {
    id: "rst-tee-002",
    slug: "the-mom-tee",
    name: "The Mom Tee",
    shortName: "Mom Tee",
    price: 34,
    category: "Tees",
    collections: ["best-sellers", "women", "matching"],
    audience: ["Mom"],
    description: "An easy, thoughtfully oversized tee with extra room through the body and sleeves that land exactly where you want them.",
    details: ["Soft drop shoulder", "Longer back hem", "Nursing-friendly relaxed neckline", "Shrink-resistant wash treatment"],
    fit: "Intentionally oversized with a soft drape.",
    fabric: "100% long-staple combed cotton, 6.5 oz.",
    image: "/images/collection-mom.png",
    imagePosition: "center 35%",
    colors: [coreColors.oatmeal, coreColors.rose, coreColors.cream, coreColors.sage],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    badge: "Mom favorite",
    rating: 4.9,
    reviewCount: 96,
  },
  {
    id: "rst-tee-003",
    slug: "the-dad-tee",
    name: "The Dad Tee",
    shortName: "Dad Tee",
    price: 34,
    category: "Tees",
    collections: ["best-sellers", "men", "matching"],
    audience: ["Dad"],
    description: "A substantial everyday tee with clean lines, easy room, and a collar built to survive weekends, wash days, and repeat.",
    details: ["Structured relaxed fit", "Double-needle collar", "Garment washed for softness", "Shrink-resistant wash treatment"],
    fit: "Relaxed through chest and body. True to size.",
    fabric: "100% long-staple combed cotton, 6.5 oz.",
    image: "/images/collection-dad.png",
    imagePosition: "center 35%",
    colors: [coreColors.blue, coreColors.cream, coreColors.gray, coreColors.ink],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    rating: 4.8,
    reviewCount: 81,
  },
  {
    id: "rst-kids-001",
    slug: "the-little-tee",
    name: "The Little Tee",
    shortName: "Little Tee",
    price: 30,
    category: "Kids",
    collections: ["kids", "matching", "toddler"],
    audience: ["Toddler", "Kids"],
    description: "All the softness and staying power of our grown-up tee, sized for snack breaks, floor time, and big little adventures.",
    details: ["Tag-free neck", "Easy-on neckline", "Extra durable seams", "Shrink-resistant wash treatment"],
    fit: "Relaxed and play-ready with room to grow.",
    fabric: "100% combed cotton, 6.0 oz.",
    image: "/images/collection-kids.png",
    imagePosition: "center 32%",
    colors: [coreColors.sage, coreColors.terra, coreColors.cream, coreColors.blue],
    sizes: ["2T", "3T", "4T", "5T", "YXS", "YS", "YM", "YL"],
    badge: "Matching sizes",
    rating: 4.9,
    reviewCount: 63,
  },
  {
    id: "rst-baby-001",
    slug: "the-baby-soft-tee",
    name: "The Baby Soft Tee",
    shortName: "Baby Soft Tee",
    price: 30,
    category: "Baby",
    collections: ["baby", "matching"],
    audience: ["Baby"],
    description: "A buttery-soft first tee with gentle stretch, easy shoulder snaps, and enough substance for hand-me-down life.",
    details: ["Nickel-free shoulder snaps", "Flatlock side seams", "Tag-free neck", "Pre-washed and shrink resistant"],
    fit: "Easy fit with room for movement and layering.",
    fabric: "95% organic cotton, 5% elastane.",
    image: "/images/collection-mom.png",
    imagePosition: "center 65%",
    colors: [coreColors.cream, coreColors.oatmeal, coreColors.rose, coreColors.sage],
    sizes: ["0-3M", "3-6M", "6-12M", "12-18M", "18-24M"],
    badge: "New",
    rating: 5,
    reviewCount: 27,
  },
  {
    id: "rst-layer-001",
    slug: "the-slow-morning-long-sleeve",
    name: "The Slow Morning Long Sleeve",
    shortName: "Slow Morning Long Sleeve",
    price: 42,
    category: "Long Sleeves",
    collections: ["women", "men", "layers"],
    audience: ["Mom", "Dad"],
    description: "A soft, weighty long sleeve for cool kitchens, porch coffee, and every quiet hour in between.",
    details: ["Soft rib cuffs", "Relaxed drop shoulder", "Garment washed", "Holds its shape wash after wash"],
    fit: "Relaxed unisex fit. Size down for less volume.",
    fabric: "100% long-staple combed cotton, 7 oz.",
    image: "/images/hero-family.png",
    imagePosition: "70% center",
    colors: [coreColors.cream, coreColors.gray, coreColors.sage, coreColors.ink],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    rating: 4.8,
    reviewCount: 45,
  },
  {
    id: "rst-layer-002",
    slug: "the-stay-in-crewneck",
    name: "The Stay-In Crewneck",
    shortName: "Stay-In Crewneck",
    price: 62,
    category: "Crewnecks",
    collections: ["best-sellers", "women", "men", "layers"],
    audience: ["Mom", "Dad"],
    description: "Dense on the outside, cloud-soft inside. A refined everyday crewneck without the stiff, boxy sweatshirt feeling.",
    details: ["Brushed fleece interior", "Set-in rib side panels", "Shape-retaining cuffs", "Pre-shrunk construction"],
    fit: "Roomy, polished unisex fit.",
    fabric: "80% cotton, 20% recycled polyester, 10.5 oz.",
    image: "/images/tees-flatlay.png",
    imagePosition: "center center",
    colors: [coreColors.oatmeal, coreColors.gray, coreColors.blue, coreColors.ink],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    badge: "Cloud-soft",
    rating: 4.9,
    reviewCount: 72,
  },
  {
    id: "rst-layer-003",
    slug: "the-porch-light-hoodie",
    name: "The Porch Light Hoodie",
    shortName: "Porch Light Hoodie",
    price: 74,
    category: "Hoodies",
    collections: ["women", "men", "layers"],
    audience: ["Mom", "Dad"],
    description: "Our premium heavyweight hoodie, softened from the first wear with a generous hood and quietly structured shape.",
    details: ["Double-layer hood", "No drawstrings", "Brushed fleece interior", "Pre-shrunk construction"],
    fit: "Oversized with a clean shoulder and roomy body.",
    fabric: "80% cotton, 20% recycled polyester, 12 oz.",
    image: "/images/hero-family.png",
    imagePosition: "28% center",
    colors: [coreColors.cream, coreColors.sage, coreColors.blue, coreColors.ink],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    rating: 4.9,
    reviewCount: 38,
  },
  {
    id: "rst-lounge-001",
    slug: "the-reset-short",
    name: "The Reset Short",
    shortName: "Reset Short",
    price: 38,
    category: "Lounge",
    collections: ["women", "men", "lounge"],
    audience: ["Mom", "Dad"],
    description: "Pull-on French terry shorts made for the first quiet hour home, with a soft waistband and useful pockets.",
    details: ["Wide comfort waistband", "Deep side pockets", "Soft-touch drawcord", "Pre-washed"],
    fit: "Relaxed with a 5.5-inch inseam.",
    fabric: "100% cotton French terry, 8 oz.",
    image: "/images/collection-dad.png",
    imagePosition: "center 70%",
    colors: [coreColors.oatmeal, coreColors.gray, coreColors.sage, coreColors.ink],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    rating: 4.8,
    reviewCount: 34,
  },
  {
    id: "rst-lounge-002",
    slug: "the-soft-hour-pant",
    name: "The Soft Hour Pant",
    shortName: "Soft Hour Pant",
    price: 54,
    category: "Lounge",
    collections: ["women", "men", "lounge"],
    audience: ["Mom", "Dad"],
    description: "A straight-leg lounge pant that feels like staying in and looks considered enough to step out.",
    details: ["Soft elastic waist", "Straight relaxed leg", "Deep side pockets", "Pre-shrunk"],
    fit: "Easy mid-rise fit with a 29-inch inseam.",
    fabric: "100% cotton French terry, 8 oz.",
    image: "/images/collection-mom.png",
    imagePosition: "center 75%",
    colors: [coreColors.oatmeal, coreColors.gray, coreColors.sage, coreColors.ink],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    rating: 4.9,
    reviewCount: 41,
  },
  {
    id: "rst-set-001",
    slug: "the-family-home-set",
    name: "The Family Home Set",
    shortName: "Family Home Set",
    price: 112,
    compareAtPrice: 128,
    category: "Sets",
    collections: ["best-sellers", "matching"],
    audience: ["Family"],
    description: "Four matching Home Tees for the people who make home feel like home. Choose each size after ordering.",
    details: ["Includes two adult tees and two kids tees", "Mix sizes and colors", "Gift-ready packaging", "Save $16 as a set"],
    fit: "Relaxed fits for grown-ups and kids.",
    fabric: "100% long-staple combed cotton.",
    image: "/images/hero-family.png",
    imagePosition: "center center",
    colors: [coreColors.cream, coreColors.oatmeal, coreColors.sage, coreColors.blue],
    sizes: ["Build your set"],
    badge: "Family bundle",
    rating: 5,
    reviewCount: 22,
  },
  {
    id: "rst-set-002",
    slug: "the-new-mom-comfort-set",
    name: "The New Mom Comfort Set",
    shortName: "New Mom Comfort Set",
    price: 82,
    compareAtPrice: 92,
    category: "Sets",
    collections: ["women", "lounge"],
    audience: ["Mom"],
    description: "Our roomy Mom Tee and Soft Hour Pant together in an easy, giftable set made for slow recovery days and softer nights.",
    details: ["Includes Mom Tee and Soft Hour Pant", "Nursing-friendly neckline", "Gift note available", "Save $10 as a set"],
    fit: "Relaxed, forgiving, and designed to move with you.",
    fabric: "Long-staple cotton tee and cotton French terry pant.",
    image: "/images/collection-mom.png",
    colors: [coreColors.oatmeal, coreColors.rose, coreColors.cream],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    badge: "Giftable",
    rating: 5,
    reviewCount: 19,
  },
];

export const collections = [
  { slug: "women", name: "For Mom", description: "Roomy, considered comfort for every version of the day.", image: "/images/collection-mom.png" },
  { slug: "men", name: "For Dad", description: "Substantial essentials, softened from the start.", image: "/images/collection-dad.png" },
  { slug: "kids", name: "For Littles", description: "Play-ready softness made to wash, wear, and hand down.", image: "/images/collection-kids.png" },
  { slug: "matching", name: "Match at Home", description: "Quietly coordinated colors and fits for the whole family.", image: "/images/hero-family.png" },
  { slug: "lounge", name: "Lounge", description: "Easy layers and soft hours, made for staying close.", image: "/images/tees-flatlay.png" },
];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getCollection(slug: string) {
  return collections.find((collection) => collection.slug === slug);
}

export const formatPrice = (price: number) =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(price);
