// Downloads Printful's photorealistic per-color mockups into public/mockups/
// and writes src/data/mockups.json (slug -> color -> image path).
// Run AFTER `npm run printful:sync`. Usage: npm run printful:mockups

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";

for (const file of [".env.local", ".env"]) {
  if (existsSync(file)) {
    for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
      const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
      if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^["']|["']$/g, "");
    }
  }
}

const KEY = process.env.PRINTFUL_API_KEY;
if (!KEY) {
  console.error("PRINTFUL_API_KEY is not set. Add it to .env.local first (docs/PRINTFUL-SETUP.md).");
  process.exit(1);
}

const SLUGS = {
  "rst-mom-001": "the-mom-tee",
  "rst-dad-001": "the-dad-tee",
  "rst-baby-001": "the-baby-tee",
  "rst-little-001": "the-little-tee",
};

const map = JSON.parse(readFileSync("src/data/printful-map.json", "utf8"));
if (!Object.keys(map.products ?? {}).length) {
  console.error("printful-map.json is empty — run `npm run printful:sync` first.");
  process.exit(1);
}

async function pf(path) {
  const response = await fetch(`https://api.printful.com${path}`, { headers: { Authorization: `Bearer ${KEY}` } });
  const body = await response.json();
  if (!response.ok) throw new Error(`Printful ${path} -> ${response.status}: ${JSON.stringify(body.error ?? body)}`);
  return body.result;
}

const mockups = { $comment: "Generated by `npm run printful:mockups`. Do not edit by hand." };
let saved = 0;

for (const [productId, entry] of Object.entries(map.products)) {
  if (productId.startsWith("$")) continue;
  const slug = SLUGS[productId];
  if (!slug || !entry.syncProductId) continue;
  const detail = await pf(`/store/products/${entry.syncProductId}`);
  mkdirSync(`public/mockups/${slug}`, { recursive: true });
  const seenColors = new Set();
  for (const sv of detail.sync_variants) {
    const tail = sv.name.includes(" - ") ? sv.name.split(" - ").pop() : sv.name;
    const rawColor = tail.split(" / ")[0]?.trim();
    // find this variant's generated preview mockup
    const preview = (sv.files ?? []).find((f) => f.type === "preview" && f.preview_url);
    if (!rawColor || !preview || seenColors.has(rawColor)) continue;
    seenColors.add(rawColor);
    // resolve the RST color name from the sync map keys (already aliased by printful:sync)
    const matched = Object.keys(entry.variants).find((k) => entry.variants[k].syncVariantId === sv.id);
    const color = matched ? matched.split("|")[0] : rawColor;
    const fileName = `${color.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.jpg`;
    const image = await fetch(preview.preview_url);
    if (!image.ok) { console.warn(`  ? download failed for ${sv.name}`); continue; }
    writeFileSync(`public/mockups/${slug}/${fileName}`, Buffer.from(await image.arrayBuffer()));
    mockups[slug] = mockups[slug] ?? {};
    mockups[slug][color] = `/mockups/${slug}/${fileName}`;
    saved++;
    console.log(`✓ ${slug} / ${color}`);
  }
}

writeFileSync("src/data/mockups.json", JSON.stringify(mockups, null, 2) + "\n");
console.log(`\nWrote ${saved} mockups + src/data/mockups.json. Rebuild/redeploy to ship them.`);
