// Syncs your Printful store products into src/data/printful-map.json.
// Prerequisites (see docs/PRINTFUL-SETUP.md):
//   1. PRINTFUL_API_KEY in .env.local
//   2. Four products created in your Printful store, named EXACTLY:
//      "The Mom Tee", "The Dad Tee", "The Baby Tee", "The Little Tee"
// Usage: npm run printful:sync

import { readFileSync, writeFileSync, existsSync } from "node:fs";

for (const file of [".env.local", ".env"]) {
  if (existsSync(file)) {
    for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
      const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
      if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^["']|["']$/g, "");
    }
  }
}

const KEY = process.env.PRINTFUL_API_KEY;
if (!KEY) {
  console.error("PRINTFUL_API_KEY is not set. Add it to .env.local first (docs/PRINTFUL-SETUP.md, step 2).");
  process.exit(1);
}

// Printful product name -> RST catalog product id (src/lib/catalog.ts)
const PRODUCT_IDS = {
  "The Mom Tee": "rst-mom-001",
  "The Dad Tee": "rst-dad-001",
  "The Baby Tee": "rst-baby-001",
  "The Little Tee": "rst-little-001",
};

// Printful's garment color names -> RST display color names. These match the
// actual Comfort Colors / Bella colors used when the products were created.
const COLOR_ALIASES = {
  "Ivory": "Cream",
  "White": "Cream",
  "Hemp": "Oatmeal",
  "Khaki": "Sand",
  "Granite": "Taupe",
  "Grey": "Heather Gray",
  "Pepper": "Washed Black",
  "Chambray": "Chambray",
};

async function pf(path) {
  const response = await fetch(`https://api.printful.com${path}`, { headers: { Authorization: `Bearer ${KEY}` } });
  const body = await response.json();
  if (!response.ok) throw new Error(`Printful ${path} -> ${response.status}: ${JSON.stringify(body.error ?? body)}`);
  return body.result;
}

const list = await pf("/store/products?limit=100");
const map = { $comment: "Generated by `npm run printful:sync`. Do not edit by hand.", products: {} };
let mapped = 0, skipped = [];

const catalogCache = {};
async function catalogVariants(catalogProductId) {
  if (!catalogCache[catalogProductId]) {
    const d = await pf(`/products/${catalogProductId}`);
    catalogCache[catalogProductId] = Object.fromEntries(d.variants.map((v) => [v.id, { color: v.color, size: v.size }]));
  }
  return catalogCache[catalogProductId];
}

for (const item of list) {
  const productId = PRODUCT_IDS[item.name];
  if (!productId) { skipped.push(item.name); continue; }
  const detail = await pf(`/store/products/${item.id}`);
  const variants = {};
  for (const sv of detail.sync_variants) {
    // Resolve true color + size from the catalog variant, not the sync name
    // (API-created variants don't carry color/size in their display name).
    const catalogId = sv.product?.product_id;
    const lookup = catalogId ? await catalogVariants(catalogId) : {};
    const meta = lookup[sv.variant_id];
    if (!meta) { console.warn(`  ? No catalog match for variant ${sv.variant_id} — skipping`); continue; }
    const color = COLOR_ALIASES[meta.color] ?? meta.color;
    variants[`${color}|${meta.size}`] = { syncVariantId: sv.id };
    mapped++;
  }
  map.products[productId] = { syncProductId: item.id, variants };
  console.log(`✓ ${item.name}: ${Object.keys(variants).length} variants`);
}

writeFileSync("src/data/printful-map.json", JSON.stringify(map, null, 2) + "\n");
console.log(`\nWrote src/data/printful-map.json (${mapped} variants).`);
if (skipped.length) console.log(`Skipped unrecognized Printful products: ${skipped.join(", ")}`);
const missing = Object.values(PRODUCT_IDS).filter((id) => !map.products[id]);
if (missing.length) console.log(`⚠ Not found in your Printful store yet: ${missing.join(", ")} — create them (exact names) and re-run.`);
console.log("Next: npm run printful:mockups");
