// Syncs your Printful store products into src/data/printful-map.json.
// Prerequisites (see docs/PRINTFUL-SETUP.md):
//   1. PRINTFUL_API_KEY in .env.local
//   2. Four products created in your Printful store, named EXACTLY:
//      "The Mom Tee", "The Dad Tee", "The Baby Tee", "The Little Tee"
// Usage: npm run printful:sync

import { readFileSync, writeFileSync, existsSync } from "node:fs";

for (const file of [".env.local", ".env"]) {
  if (existsSync(file)) {
    for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
      const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
      if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^["']|["']$/g, "");
    }
  }
}

const KEY = process.env.PRINTFUL_API_KEY;
if (!KEY) {
  console.error("PRINTFUL_API_KEY is not set. Add it to .env.local first (docs/PRINTFUL-SETUP.md, step 2).");
  process.exit(1);
}

// Printful product name -> RST catalog product id (src/lib/catalog.ts)
const PRODUCT_IDS = {
  "The Mom Tee": "rst-mom-001",
  "The Dad Tee": "rst-dad-001",
  "The Baby Tee": "rst-baby-001",
  "The Little Tee": "rst-little-001",
};

// Printful's garment color names -> RST color names. Adjust the left side to
// whatever colors you picked for the garments in Printful.
const COLOR_ALIASES = {
  "Natural": "Cream",
  "Cream": "Cream",
  "Vintage White": "Cream",
  "Oatmeal": "Oatmeal",
  "Heather Dust": "Oatmeal",
  "Tan": "Sand",
  "Sand": "Sand",
  "Heather Tan": "Sand",
  "Pebble Brown": "Taupe",
  "Taupe": "Taupe",
  "Athletic Heather": "Heather Gray",
  "Heather Gray": "Heather Gray",
  "Heather Grey": "Heather Gray",
  "Black Heather": "Washed Black",
  "Washed Black": "Washed Black",
  "Vintage Black": "Washed Black",
};

async function pf(path) {
  const response = await fetch(`https://api.printful.com${path}`, { headers: { Authorization: `Bearer ${KEY}` } });
  const body = await response.json();
  if (!response.ok) throw new Error(`Printful ${path} -> ${response.status}: ${JSON.stringify(body.error ?? body)}`);
  return body.result;
}

const list = await pf("/store/products?limit=100");
const map = { $comment: "Generated by `npm run printful:sync`. Do not edit by hand.", products: {} };
let mapped = 0, skipped = [];

for (const item of list) {
  const productId = PRODUCT_IDS[item.name];
  if (!productId) { skipped.push(item.name); continue; }
  const detail = await pf(`/store/products/${item.id}`);
  const variants = {};
  for (const sv of detail.sync_variants) {
    // sync variant names look like "The Mom Tee - Natural / XS"
    const tail = sv.name.includes(" - ") ? sv.name.split(" - ").pop() : sv.name;
    const [rawColor, rawSize] = tail.split(" / ").map((s) => s.trim());
    const color = COLOR_ALIASES[rawColor] ?? rawColor;
    if (!rawSize) { console.warn(`  ? Could not parse size from "${sv.name}" — skipping variant`); continue; }
    variants[`${color}|${rawSize}`] = { syncVariantId: sv.id };
    mapped++;
  }
  map.products[productId] = { syncProductId: item.id, variants };
  console.log(`✓ ${item.name}: ${Object.keys(variants).length} variants`);
}

writeFileSync("src/data/printful-map.json", JSON.stringify(map, null, 2) + "\n");
console.log(`\nWrote src/data/printful-map.json (${mapped} variants).`);
if (skipped.length) console.log(`Skipped unrecognized Printful products: ${skipped.join(", ")}`);
const missing = Object.values(PRODUCT_IDS).filter((id) => !map.products[id]);
if (missing.length) console.log(`⚠ Not found in your Printful store yet: ${missing.join(", ")} — create them (exact names) and re-run.`);
console.log("Next: npm run printful:mockups");
